<?php include "pageStart.phtml" ?>

<?php include "navbar.phtml" ?>

<div class="container container-books">

    

    <nav class="navbar navbar-fixed-top books-configure-view">
        <div class="container-fluid">
            
            <div class="navbar-header">
            </div>
            <ul class="nav navbar-nav">
                <li>
                    <a href="zanr">
                        Třídit podle žánru
                    </a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <?php if (Session::exists("logged_in")): ?>
                    <a href="knihy/vytvorit" class="navbar-brand">Nová kniha</a>
                <?php endif ?>
            </ul>
        </div>
    </nav>




    <div class="table-book-view">
        <table class="table table-hover table-inverse">
            <thead>
                <tr>
                    <th>Thumb</th>
                    <th>Název</th>
                    <th>Autor</th>
                    <th>Hlasů</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($books as $book): ?>
                <tr>
                    <td>
                        <a href="knihy/<?= $book['id'] ?>/<?= $book['book_url'] ?>">
                            <img
                                src="<?= strlen($book['picture_url']) > 0? $book['picture_url'] : 'http://resources.macmillanusa.com/jackets/186W/0000000000001.jpg' ?>"
                                alt="<?= $book['name'] ?> - obrázek"
                                class = "img-responsive img-rounded"
                                width="50">
                        </a>
                    </td>
                    <td>
                        <?= $book['name'] ?>
                    </td>
                    <td>
                        <a href="uzivatele/<?= $username ?>">
                            <?= $username ?>
                        </a>
                    </td>
                    <td>
                        <?= $book['upvotes'] ?>
                    </td>
                </tr>
                <?php endforeach ?>
            </tbody>
        </table>
    </div>

</div>



<?php include "pageEnd.phtml" ?>