<?php include "pageStart.phtml" ?>

<?php include "navbar.phtml" ?>

<div class="container container-books">

    

    <nav class="navbar">
        <div class="container-fluid">
            
            <div class="navbar-header">
            </div>
            <ul class="nav navbar-nav">
                <li>
                    <a href="zanr">
                        Třídit podle žánru
                    </a>
                </li>
            </ul>
            <div class="nav navbar-nav navbar-right">
                <?php if (Session::exists("logged_in")): ?>
                    <a href="knihy/vytvorit" class="navbar-brand">Nová kniha</a>
                <?php endif ?>
            </div>
        </div>
    </nav>




    <div class="table-book-view">
        <table class="table table-hover table-inverse">
            <thead>
                <tr>
                    <th>Thumb</th>
                    <th>Název</th>
                    <th>Autor</th>
                    <th>Hlasů</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($books as $book): ?>
                <tr>
                    <td>
                        <a href="knihy/<?= $book['book_id'] ?>/<?= $book['book_url'] ?>">
                            <img
                                src="<?= strlen($book['book_picture_url']) > 0? $book['book_picture_url'] : 'http://resources.macmillanusa.com/jackets/186W/0000000000001.jpg' ?>"
                                class = "img-responsive img-rounded"
                                width="50"
                                alt="<?= $book['book_name'] ?> - obrázek">
                        </a>
                    </td>
                    <td>
                        <?= $book['book_name'] ?>
                    </td>
                    <td>
                        <a href="uzivatele/<?= $book['username'] ?>">
                        <?= $book['username'] ?>
                        </a>
                    </td>
                    <td>
                        <?= $book['book_upvotes'] ?>
                    </td>
                </tr>
                <?php endforeach ?>
            </tbody>
        </table>
    </div>

</div>



<?php include "pageEnd.phtml" ?>