<?php include "pageStart.phtml" ?>

<?php include "navbar.phtml" ?>

<div class="container container-books">
    
    <div class="text-center">
        <h1>Login</h1>
        <a href="<?= $fbUrl ?>" class="btn btn-primary">Přihlásit se pomocí facebooku</a>
        <p>
            <a href="<?= $fbUrl ?>">
                <small><i>Registrovat se</i></small>
            </a>
        </p>
    </div>

</div>



<?php include "pageEnd.phtml" ?>