<nav class="navbar navbar-inverse">
    <div class="container-fluid moss-green-bg">
        <div class="navbar-header">
            <a
                class="navbar-brand"
                    <?php if (Session::exists('fb_id')): ?>
                        href="zed"
                    <?php else: ?>
                        href="login"
                    <?php endif ?>
                >
                Knihomol
            </a>
        </div>
        <ul class="nav navbar-nav">
            <?php if (Session::exists('fb_id')): ?>
                <li class="<?= ViewUtils::activeClass('active', 'zed') ?>"><a href="zed">Zeď</a></li>
            <?php endif ?>
            <li class="<?= ViewUtils::activeClass('active', 'knihy') ?>"><a href="knihy">Knihy</a></li>
            <li class="<?= ViewUtils::activeClass('active', 'uzivatele') ?>"><a href="uzivatele">Uživatelé</a></li>
            <?php if (Session::exists('fb_id')): ?>
                <li class="<?= ViewUtils::activeClass('active', 'odber') ?>"><a href="odber">Moje odběry</a></li>
                 <li class="<?= ViewUtils::activeClass('active', 'odznak') ?>"><a href="odznak">Odznaky</a></li>
            <?php endif ?>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <?php if (Session::exists('fb_id')): ?>
                <li>
                    <a href="zed"><span class="glyphicon glyphicon-user nav-icon"></span>
                        Přihlášen jako <?= Session::get('username') ?> 
                    </a>
                </li>
                <li>
                    <a href="login/odhlasit-se"><span class="glyphicon glyphicon-user nav-icon"></span>
                        Odhlásit se
                    </a>
                </li>
            <?php else: ?>
                <li><a href="login"><span class="glyphicon glyphicon-user nav-icon"></span>Registrovat se</a></li>
                <li><a href="login"><span class="glyphicon glyphicon-log-in nav-icon"></span>Přihlásit</a></li>
            <?php endif ?>
        </ul>
    </div>
</nav>