<?php include "pageStart.phtml" ?>

<?php include "navbar.phtml" ?>

<div class="container">

    <nav class="navbar navbar-fixed-top story-show-second-nav hover-menu-chapter">
        <div class="container-fluid">
            
            <div class="navbar-header">
                <a class="navbar-brand" id="nadpis">
                    <?= $story['name'] ?>
                </a>
            </div>
            <div class="btn-group inline pull-right margin-top">
                <div class="inline margin-right">
                    <?= $story['upvotes'] ?>
                </div>
                <form class="inline" method="POST" action="upvote/do">
                    <input type="hidden" value="<?= $story['id'] ?>" name="id"/>
                    <input type="hidden" value="1" name="vote"/>
                    <input type="hidden" value="story" name="type"/>

                    <button class="btn btn-sm btn-success">
                        <span class="glyphicon glyphicon-plus"></span>
                    </button>
                </form>

                <form class="inline" method="POST" action="upvote/do">
                    <input type="hidden" value="<?= $story['id'] ?>" name="id"/>
                    <input type="hidden" value="-1" name="vote"/>
                    <input type="hidden" value="story" name="type"/>

                    <button class="btn btn-sm btn-danger">
                        <span class="glyphicon glyphicon-minus"></span>
                    </button>
                </form>
            </div>
        </div>
    </nav>


    


    <div class="container-books book-text text-justify">
        <?= $story['text'] ?>
    </div>


</div>

<!--<div class="progress-bar-chapter footer navbar-fixed-bottom">

</div>-->

<nav class="navbar navbar-fixed-bottom story-show-second-nav hover-menu-chapter">
        <div class="container-fluid">
            
            <div class="navbar-header">
                <a class="navbar-brand" href="komentare/<?= $story['id'] ?>/<?= $story['url'] ?>">
                    <span class="glyphicon glyphicon-comment"></span>
                </a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <?php if (true): ?>
                    <li>
                        <a href="povidky/<?= $story['id'].'/'.$story['url']?>/upravit">
                            <span class="glyphicon glyphicon-pencil"></span>
                        </a>
                    </li> 
                <?php endif ?>
                <li>
                    <a id="postup">
                        <span class="glyphicon glyphicon glyphicon-arrow-right nav-icon"></span>
                            Postup kapitolou:
                            <span class="chapter-progress">10</span> %
                    </a>
                </li>
            </ul>
        </div>
    </nav>



<?php include "pageEnd.phtml" ?>