<?php include "pageStart.phtml" ?>

<?php include "navbar.phtml" ?>

<div class="container container-books">
    <form method="POST">

        <div class="form-group">   
            <label class="control-label">Název:</label>
            <input type="text" name="name" class="form-control" />
        </div>

        <div class="form-group">   
            <label class="control-label">Text:</label>
            <textarea name="text" class="form-control"></textarea>
        </div>

        </br>

        <button class="btn btn-primary center-block form-control">
            Vytvořit
        </button>

    </form>



    <script src="//tinymce.cachefly.net/4.0/tinymce.min.js"></script>
    <script>
            tinymce.init({
                    selector: "textarea[name=text]",
                    plugins: [
                            "advlist autolink lists link image charmap print preview anchor",
                            "searchreplace visualblocks code fullscreen",
                    ],
                    toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent",
                    entities: "160,nbsp",
                    entity_encoding: "named",
                    entity_encoding: "raw"
            });
    </script>

<?php include "pageEnd.phtml" ?>