<?php include "pageStart.phtml" ?>

<?php include "navbar.phtml" ?>

<div class="container">

    <nav class="navbar navbar-fixed-top story-show-second-nav hover-menu-chapter">
        <div class="container-fluid">
            
            <div class="navbar-header">
                <a class="navbar-brand" href="">
                    Název knihy - <?= $story['name'] ?> - Autor
                </a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="login"><span class="glyphicon glyphicon-heart nav-icon"></span></a></li>
                 <li><a href="login"><span class="glyphicon glyphicon-circle-arrow-left nav-icon"></span></a></li>
                  <li><a href="login"><span class="glyphicon glyphicon-circle-arrow-right nav-icon"></span></a></li>
            </ul>
        </div>
    </nav>


    


    <h2><?= $story['name'] ?></h2>

    <div class="chapter-container book-text text-justify">
        <?= $story['text'] ?>
        <?= $story['text'] ?>
        <?= $story['text'] ?>
        <?= $story['text'] ?>
        <?= $story['text'] ?>
    </div>


</div>

<!--<div class="progress-bar-chapter footer navbar-fixed-bottom">

</div>-->

<nav class="navbar navbar-fixed-bottom story-show-second-nav hover-menu-chapter">
        <div class="container-fluid">
            
            <div class="navbar-header">
                <a class="navbar-brand" href="komentare/<?= $story['id'] ?>/<?= $story['url'] ?>">
                    <span class="glyphicon glyphicon-comment"></span>
                </a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a id="text-config-btn" name="text-config-anchor">
                        <span data-toggle="modal" data-target="#text-config-modal" class="glyphicon glyphicon-text-height nav-icon"></span>
                    </a>
                </li>
                <li>
                    <a href="login">
                            <span class="glyphicon glyphicon-star nav-icon"></span>
                            <?= $story['upvotes'] ?>
                    </a>
                </li>
                <li>
                    <a href="login">
                        <span class="glyphicon glyphicon glyphicon-arrow-right nav-icon"></span>
                            Postup kapitolou:
                            <span class="chapter-progress">10</span> %
                    </a>
                </li>
            </ul>
        </div>
    </nav>



<?php include "pageEnd.phtml" ?>