<?php include "pageStart.phtml" ?>

<?php include "navbar.phtml" ?>

<?php $errors = empty($errors) ? [] : $errors ?>

<div class="container container-books">
    <form method="POST">

        <div class="form-group">   
            <label class="control-label">Název:</label>
            <input type="text" name="name" value="<?= isset($story) ? $story['name'] : '' ?>" class="form-control" />
            <?= ViewUtils::ifErrorRender("name", $errors) ?>
        </div>

        <input type="hidden" name="book_id" value="<?= $bookId ?>"/>

        <div class="form-group">   
            <label class="control-label">Text:</label>
            <textarea name="text" class="form-control" rows="30"><?= isset($story) ? $story['text'] : '' ?></textarea>
            <?= ViewUtils::ifErrorRender("text", $errors) ?>
        </div>

        </br>

        <button class="btn btn-primary center-block form-control">
            Vytvořit
        </button>

    </form>



    <script src="//tinymce.cachefly.net/4.0/tinymce.min.js"></script>
    <script>
            tinymce.init({
                    selector: "textarea[name=text]",
                    plugins: [
                            "advlist autolink lists link image charmap print preview anchor",
                            "searchreplace visualblocks code fullscreen",
                    ],
                    toolbar: "undo redo | alignleft aligncenter alignright alignjustify",
                    entities: "160,nbsp",
                    valid_elements: "div, br, p, i, strong",
                    invalid_elements: "script, object, embed, link, a, style, , iframe, input, form, b, i, strong, small",
                    entity_encoding: "named",
                    entity_encoding: "raw"
            });
    </script>

<?php include "pageEnd.phtml" ?>